# use the official Python image from the docker Hub
FROM python:3.10-slim

# set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in the requiremnet,txt
RUN pip Install flask

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python","app.py"]